name: Release

permissions:
  contents: write

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: stitch-sync
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: stitch-sync.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: stitch-sync

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev libusb-1.0-0-dev pkg-config

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Create Windows Launcher
        if: matrix.os == 'windows-latest'
        run: |
          echo "@echo off" > launch.bat
          echo "stitch-sync.exe" >> launch.bat
          echo "pause" >> launch.bat

      - name: Package Release
        run: |
          tar -czf stitch-sync-${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release ${{ matrix.artifact_name }}

      - name: Upload Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: stitch-sync-${{ matrix.target }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
